# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=200)),
                ('url_to_image', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=100)),
                ('published', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
