# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-14 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170526_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='news.Category'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='news/static/news/photos/originals/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='relatedtopic',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_topics', to='news.Article'),
        ),
    ]
