# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-14 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170614_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedtopic',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
