# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170425_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FINANCE', 'Finance'), ('GENERAL', 'General'), ('SPORTS', 'Sports'), ('TECHNOLOGY', 'Technology')], default='GENERAL', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='news.Category'),
        ),
    ]
