# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-27 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20170427_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FINANCE', 'Finance'), ('GENERAL', 'General'), ('SPORTS', 'Sports'), ('TECHNOLOGY', 'Technology')], default='GENERAL', max_length=20, unique=True),
        ),
    ]
