# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170427_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
